name: Update Files

on:
  schedule:
    - cron: "0 0 * * 3"
  workflow_dispatch:

jobs:
  update-files:
    name: Update Files
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          check-latest: true

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Fuse
        run: |
          sudo apt-get install -y fuse3 bindfs

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global credential.helper store
          echo "https://Kale-Ko:${{secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials

      - name: Get Time
        id: get-time
        run: |
          echo "time=$(date -u '+%s.%N')" >> $GITHUB_OUTPUT

      - name: Download Cache
        id: download-cache
        uses: actions/cache/restore@v4
        with:
          path: cache/
          key: full-cache-${{ steps.get-time.outputs.time }}
          restore-keys: |
            full-cache-
            full-cache

      - name: Install Dependencies
        run: bun install

      - name: Run Restore
        run: bun run restore

      - name: Run Test
        run: bun run test

      - name: Run Output
        run: bun run output --create-restore

      - name: Clear invalid versions
        run: |
          rm -f cache/git-completion/75bf72d8e4b38cf5f729637efc116697edec4334 cache/git-completion/4a0126da466f90d6e52eb3e27332f7f7070f4be8 cache/git-completion/dee854f57cac0fc9f1b96b96254a67829dd103ae cache/git-completion/0525ae4750d18d6c3cf9edee1f510333919c6003 cache/git-completion/1d0ccfff5f8d13d3ecaddbc481a9a4815e312e4e cache/git-completion/656e98e9c5a418b4747b0e5892fd301963b0bcc7 cache/git-completion/157959b1daeda81293854032102eef36e76af108 cache/git-completion/93ca7217fa9027019328b1b8f9b2e8f82436622d cache/git-completion/af8a6b1a9d8d44e080451553060a602e1214a7bb cache/git-completion/fcbaaa318bf47cecb0c37da7a37903e4bcf24e90 cache/git-completion/76dd36e6b4fb2db5e474dd3b44cd96f3f498433dgit push -d origin 1_14_2_pre-release_4
          git push -d origin 1_14_2_pre-release_3
          git push -d origin 1_14_2_pre-release_2
          git push -d origin 1_14_2_pre-release_1
          git push -d origin 1_14_1_pre-release_2
          git push -d origin 1_14_1_pre-release_1
          git push -d origin 1_14_pre-release_5
          git push -d origin 1_14_pre-release_4
          git push -d origin 1_14_pre-release_3
          git push -d origin 1_14_pre-release_2
          git push -d origin 1_14_pre-release_1

      - name: Run Git
        run: bun run git

      - name: Upload Cache
        id: upload-cache
        uses: actions/cache/save@v4
        with:
          path: cache/
          key: ${{ steps.download-cache.outputs.cache-primary-key }}
        if: ${{ steps.download-cache.outcome == 'success' }}
